// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQscrpTcaBJnsIUxAUGbmbj4Fak4uRZK8',
    appId: '1:766652088817:web:9919991c981dce91b34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    authDomain: 'ecomm-af340.firebaseapp.com',
    storageBucket: 'ecomm-af340.firebasestorage.app',
    measurementId: 'G-85851L22PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgcQuww4N0D6Kl5HXgT0gpg_uQ-7AVjA',
    appId: '1:766652088817:android:ffcd2c11a5a54df1b34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    storageBucket: 'ecomm-af340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5WaYRLn2dupmNpMYlYO_K0zj46sxRZY',
    appId: '1:766652088817:ios:c0c156f1a5306979b34450',
    messagingSenderId: '766652088817',
    projectId: 'ecomm-af340',
    storageBucket: 'ecomm-af340.firebasestorage.app',
    androidClientId: '766652088817-0pkmq30h6pnnq7s7kp72ng68ja2ag40j.apps.googleusercontent.com',
    iosClientId: '766652088817-ja4jp3flo8q6vkb70joosqpm0s3k71j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
